version: "3"

services:

  flask-app:
    image: so-tag-flask
    container_name: so-tag-flask
    environment:
      - discovery.type=single-node
    ports:
      - 5000:5000
      
  react:
    image: so-tag-react
    container_name: so-tag-react
    depends_on:
      - flask-app
    environment:
      - discovery.type=single-node
    ports:
      - 3000:80